site_name: Gravel
theme:
  name: material
nav: 
  - Home: index.md
  - Rules:
     - 'Character Creation': rules/character_creation.md
     - 'General Gameplay': rules/general_gameplay.md
     - 'Arcnet and Slicing': rules/arcnet_slicing.md
     - 'Tools and Equipment': rules/tools_equipment.md
